function BACadj(varargin)
% seleciona imagem e faz background e ajustes de brilho e contraste
close all; 
% clear; 
clc;
disp(nargin)
%% imagem de entrada
% original=im2double(imread('cameraman.tif'));
original=varargin{1};
setappdata(0,'original',original);

%% figuras original e modificada
mostra(original)


%% slider
meuslider

%
%  uicontrol('Style','slider',...
%       'Parent',fig_slider,...
%       'Max',1,...
%       'Min',0,...
%       'Value',0.5,...
%       'Units','normalized',...
%       'Position',[.85 .1724 .6897 .0357],...
%       'SliderStep',[.005 .002])
%
%  uicontrol('Style','slider',...
%       'Parent',fig_slider,...
%       'Max',1,...
%       'Min',0,...
%       'Value',0.5,...
%       'Units','normalized',...
%       'Position',[.8 .1724 .6897 .0357],...
%       'SliderStep',[.005 .002])
%
%   uicontrol('Style','slider',...
%       'Parent',fig_slider,...
%       'Max',1,...
%       'Min',0,...
%       'Value',0.5,...
%       'Units','normalized',...
%       'Position',[.75 .1724 .6897 .0357],...
%       'SliderStep',[.005 .002])

%,...
%       'Callback',@(src,event)slider_cb(seal))
%   'Callback',@(src,event)slider_cb(seal))
end

function setaredit(varargin)
% string das caixas
set(findobj(gcf,'Tag','low_in_edit'),'String',num2str(get(findobj(gcf,'tag','low_in'),'Value')))
set(findobj(gcf,'Tag','high_in_edit'),'String',num2str(get(findobj(gcf,'tag','high_in'),'Value')))
set(findobj(gcf,'Tag','low_out_edit'),'String',num2str(get(findobj(gcf,'tag','low_out'),'Value')))
set(findobj(gcf,'Tag','high_out_edit'),'String',num2str(get(findobj(gcf,'tag','high_out'),'Value')))
set(findobj(gcf,'Tag','gama_edit'),'String',num2str(get(findobj(gcf,'tag','gama'),'Value')))
modifica;
end

function setarslider(varargin)
% seta dos sliders
li=findobj(gcf,'Tag','low_in');     lie=str2num(get(findobj(gcf,'tag','low_in_edit'),'String'));%#ok<ST2NM>
hi=findobj(gcf,'Tag','high_in');    hie=str2num(get(findobj(gcf,'tag','high_in_edit'),'String'));%#ok<ST2NM>
lo=findobj(gcf,'Tag','low_out');    loe=str2num(get(findobj(gcf,'tag','low_out_edit'),'String'));%#ok<ST2NM>
ho=findobj(gcf,'Tag','high_out');   hoe=str2num(get(findobj(gcf,'tag','high_out_edit'),'String'));%#ok<ST2NM>
g=findobj(gcf,'Tag','gama');        ge=str2num(get(findobj(gcf,'tag','gama_edit'),'String'));%#ok<ST2NM>

set(li,'Value',lie)
set(hi,'Value',hie)
set(lo,'Value',loe)
set(ho,'Value',hoe)
set(g,'Value',ge)
modifica;
end

function modifica

% coleta os valores 
li=findobj(gcf,'Tag','low_in');     lie=str2num(get(findobj(gcf,'tag','low_in_edit'),'String'));%#ok<ST2NM>
hi=findobj(gcf,'Tag','high_in');    hie=str2num(get(findobj(gcf,'tag','high_in_edit'),'String'));%#ok<ST2NM>
lo=findobj(gcf,'Tag','low_out');    loe=str2num(get(findobj(gcf,'tag','low_out_edit'),'String'));%#ok<ST2NM>
ho=findobj(gcf,'Tag','high_out');   hoe=str2num(get(findobj(gcf,'tag','high_out_edit'),'String'));%#ok<ST2NM>
g=findobj(gcf,'Tag','gama');        ge=str2num(get(findobj(gcf,'tag','gama_edit'),'String'));%#ok<ST2NM>


original   =getappdata(0,'original'); %% pega imagem original
modificada =imadjust(original,[lie hie],[loe hoe],ge);
mostra(original,modificada);
end
function mostra(varargin)
                
        fig_orig=figure(990);
        clf;
%         'Position',[50 400 700 250],
        set(fig_orig,'Color',[1 1 1],...
            'Tag','orig',...
            'MenuBar','none',...
            'NumberTitle','off',...
            'Name',':: Imagem original - BACBox');
        
        switch nargin
            case 1
                original=varargin{1};
                ax1=subplot(121); set(ax1,'tag','ax1');
                imshow(original,[],'parent',findobj(gcf,'tag','ax1'))
                colormap(jet)
            case 2
                original=varargin{1};
                modificada=varargin{2};
                ax1=subplot(121); set(ax1,'tag','ax1');
                imshow(original,'parent',findobj(gcf,'tag','ax1'))
                colormap(jet)
                ax2=subplot(122); set(ax2,'tag','ax2');
                imshow(modificada,'parent',findobj(gcf,'tag','ax2'))
                colormap(jet)
        end
    end

    function meuslider(varargin)
        fig_slider=figure(991);
        
        edit_high=24;
        edit_width=50;
        slider_high=.165;
        slider_width=.56;
        slider_pos_vert0=1;
        slider_pos_horiz0=.2;
        constante_pos_horiz=0;
        fig_slider_position=[100 200 250 145];
        
        set(fig_slider,'Position',fig_slider_position,'Color',[1 1 1],...
            'Tag','slider',...
            'MenuBar','none',...
            'NumberTitle','off',...
            'Name',':: Ajustes - BACBox');
        
        uicontrol('Style','slider',...
            'Parent',fig_slider,...
            'Tag','low_in',...
            'Max',1,...
            'Min',0,...
            'Value',0.5,...
            'Units','normalized',...
            'Position',[slider_pos_horiz0 slider_pos_vert0-slider_high slider_width slider_high],...
            'SliderStep',[.005 .002],...
            'Callback',@setaredit)
        
        uicontrol('Style','slider',...
            'Parent',fig_slider,...
            'Tag','high_in',...
            'Max',1,...
            'Min',0,...
            'Value',0.5,...
            'Units','normalized',...
            'Position',[slider_pos_horiz0 slider_pos_vert0-slider_high*2 slider_width slider_high],...
            'SliderStep',[.005 .002],...
            'Callback',@setaredit)
        
        uicontrol('Style','slider',...
            'Parent',fig_slider,...
            'Tag','low_out',...
            'Max',1,...
            'Min',0,...
            'Value',0.5,...
            'Units','normalized',...
            'Position',[slider_pos_horiz0 slider_pos_vert0-slider_high*3 slider_width slider_high],...
            'SliderStep',[.005 .002],...
            'Callback',@setaredit)
        
        uicontrol('Style','slider',...
            'Parent',fig_slider,...
            'Tag','high_out',...
            'Max',1,...
            'Min',0,...
            'Value',0.5,...
            'Units','normalized',...
            'Position',[slider_pos_horiz0 slider_pos_vert0-slider_high*4 slider_width slider_high],...
            'SliderStep',[.005 .002],...
            'Callback',@setaredit)
        
        uicontrol('Style','slider',...
            'Parent',fig_slider,...
            'Tag','gama',...
            'Max',5,...
            'Min',-5,...
            'Value',1,...
            'Units','normalized',...
            'Position',[slider_pos_horiz0 slider_pos_vert0-slider_high*5 slider_width slider_high],...
            'SliderStep',[.005 .002],...
            'Callback',@setaredit)
        
        
        uicontrol('Style','text',...
            'Parent',fig_slider,...
            'String','Low in',...
            'Position',[0  fig_slider_position(4)-edit_high edit_width edit_high])
        
        uicontrol('Style','text',...
            'Parent',fig_slider,...
            'String','High in',...
            'Position',[0 fig_slider_position(4)-2*edit_high edit_width edit_high])
        
        uicontrol('Style','text',...
            'Parent',fig_slider,...
            'String','Low out',...
            'Position',[0 fig_slider_position(4)-3*edit_high edit_width edit_high])
        
        uicontrol('Style','text',...
            'Parent',fig_slider,...
            'String','High out',...
            'Position',[0 fig_slider_position(4)-4*edit_high edit_width edit_high])
        
        uicontrol('Style','text',...
            'Parent',fig_slider,...
            'String','Gama',...
            'Position',[0 fig_slider_position(4)-5*edit_high edit_width edit_high])
        
        uicontrol('Style','edit',...
            'Parent',fig_slider,...
            'Tag','low_in_edit',...
            'String',num2str(get(findobj(gcf,'tag','low_in'),'Value')),...
            'Position',[fig_slider_position(3)-edit_width-constante_pos_horiz fig_slider_position(4)-edit_high edit_width edit_high],'Callback',@setarslider)
        
        uicontrol('Style','edit',...
            'Parent',fig_slider,...
            'Tag','high_in_edit',...
            'String',num2str(get(findobj(gcf,'tag','high_in'),'Value')),...
            'Position',[fig_slider_position(3)-edit_width-constante_pos_horiz fig_slider_position(4)-2*edit_high edit_width edit_high],'Callback',@setarslider)
        
        uicontrol('Style','edit',...
            'Parent',fig_slider,...
            'Tag','low_out_edit',...
            'String',num2str(get(findobj(gcf,'tag','low_out'),'Value')),...
            'Position',[fig_slider_position(3)-edit_width-constante_pos_horiz fig_slider_position(4)-3*edit_high edit_width edit_high],'Callback',@setarslider)
        
        uicontrol('Style','edit',...
            'Parent',fig_slider,...
            'Tag','high_out_edit',...
            'String',num2str(get(findobj(gcf,'tag','high_out'),'Value')),...
            'Position',[fig_slider_position(3)-edit_width-constante_pos_horiz fig_slider_position(4)-4*edit_high edit_width edit_high],'Callback',@setarslider)
        
        uicontrol('Style','edit',...
            'Parent',fig_slider,...
            'Tag','gama_edit',...
            'String',num2str(get(findobj(gcf,'tag','gama'),'Value')),...
            'Position',[fig_slider_position(3)-edit_width-constante_pos_horiz fig_slider_position(4)-5*edit_high edit_width edit_high],'Callback',@setarslider)
        
        
        set(findobj(gcf,'style','text'),'BackgroundColor',[1 1 1])
    end