function BACBox(varargin)
% tela principal do toolbox de Biosusceptometria

ph=figure(999); fundoprimeiratela(ph);      %  criar figura
clc; aux_logobiomag;                        %  limpa tela e exibe Biomag
end

function fundoprimeiratela(varargin)
clf;BACmenu(varargin{1});
textoabertura=[10,10,':: BACBox ::',...
    10,10,'',...
    10,10,'Recursos e aplicacoes',...
    ' atualmente utilizadas pelo Laboratorio de Biomagnetismo (IBB/Unesp).',...
    10,10,'Uso limitado ao Laboratorio e seus colaboradores'];
    
textodesenvolvedor=[10,10,10,'Desenvolvedor: Paulo R. Fonseca',10,...
    'prfonseca@ibb.unesp.br'];


uicontrol(gcf,'Style','text',...
                'String',textoabertura,...
                'Position',[0 100 500 250],...
                'FontSize',11,'BackGroundColor',[1 1 1]);

uicontrol(gcf,'Style','text',...
                'String',textodesenvolvedor,...
                'Position',[0 0 500 100],...
                'FontSize',9,'BackGroundColor',[1 1 1]);

axes('Parent',gcf,'units','pixels',...
     'Position',[125 300 250 250]);
imshow(imread('logo_biomag.jpg'))
% imshow(imread('logolab.png'))
end

