function BACmenu(varargin)
% cria menus para o BACBox

if nargin==0; ph=999; else ph=varargin{1}; end

clf;
set(ph,'Position',[400 200 700 500],'Color',[1 1 1],...
    'MenuBar','none',...
    'NumberTitle','off','Name',':: BACBox');

f_princ=uimenu(ph,'Label','BACBox');
uimenu(f_princ,'Label','Tela inicial','Callback',@BACBox);

f_comprimido=uimenu(ph,'Label','Comprimido');
uimenu(f_comprimido,'Label','Gerar imagens de comprimidos','Callback',@BACcomprimido);

f_backup=uimenu(f_princ,'Label','Backup');
uimenu(f_backup,'Label','Fazer backup do codigo','Callback',@back);
uimenu(f_princ,'Label','Sair de BACBox','Separator','on','Callback',@sair);

f_sinal=uimenu(ph,'Label','Sinal');
uimenu(f_sinal,'Label','Cortar sinal 20 min','Callback',@BAC20min)
uimenu(f_sinal,'Label','Buscar maximos de frequencia','Callback',@BACfft_peak)
% uimenu(f_sinal,'Label','Carregar sinal')
% uimenu(f_sinal,'Label','Cortar sinal','callback',@aux_cortasinal)
% uimenu(f_sinal,'Label','Filtrar sinal','callback',@BACfiltrasinal)



%         f11=uimenu(f1,'Label','Uma medida');
%         uimenu(f11,'Label','BAC','Callback',@medidabac);
%         uimenu(f11,'Label','For�a ou Uptake','Callback',@selecionadas);

f_mapeamento=uimenu(ph,'Label','Mapeamento');
uimenu(f_mapeamento,'Label','Processar mapeamento','CallBack',@BACmap);

f2=uimenu(ph,'Label','Tomografia');
uimenu(f2,'Label','Criar sinograma','Callback',@BACquebra)
%uimenu(f2,'Label','Carregar sinograma')
%uimenu(f2,'Label','Visualizar sinogramas','Callback',@BACviewsino)
f3=uimenu(f2,'Label','Reconstruir');
uimenu(f3,'Label','Backprojection (BP/FBP)','Callback',@BACrecon)
%uimenu(f3,'Label','EM')
f_adjuda=uimenu(ph,'Label','Ajuda');
uimenu(f_adjuda,'Label','Ajuda BACBox','Callback',@hlp);
uimenu(f_adjuda,'Label','Ultimas atualizacoes','Callback',@ultimat);
uimenu(f_adjuda,'Label','Sobre BACBox','Separator','on','Callback',@about);

end


function hlp(varargin)
clf;BACmenu(gcf);
uicontrol(gcf,'Style','text',...
                'String',['Recurso em desenvolvimento.',10,10,...
                'Para mais detalhes utilize help nomedafuncao.',10,...
                'Estao disponiveis as seguintes funcoes:'],...
                'Position',[0 200 500 300],...
                'FontSize',10,'BackGroundColor',[1 1 1]);
a=what;a=a.m;
uicontrol(gcf,'Style','edit',...
                'String',a,...
                'Position',[0 0 500 400],...
                'Max',255,'Min',0,...
                'Enable','inactive',...
                'FontSize',9,'BackGroundColor',[1 1 1]);
end

function about(varargin)
clf;BACmenu(gcf);
a=cd;a=a(end:-1:1);a=strtok(a,'\');a=a(end:-1:1);
texto=['::',a,10,10,'Este conjunto de rotinas foi desenvolvido durante o projeto ',...
    'Tomografia por Biosusceptometria de Corrente Alternada (TBAC): Desenvolvimento, caracteriza��o, implementa��o computacional e aplica��o.',...
    'Os direitos de uso pertecem ao Laboratorio de Biomagnetismo (IBB/Unesp) e seus colaboradores.',10,10,...
    '::DESENVOLVEDOR:',10,10,...
    'Paulo Roberto da Fonseca Filho',10,'prfonseca@ibb.unesp.br / prfonseca@gmail.com',10,10,...
    '::COLABORADORES:',10,10,...
    'Rodrigo Sartorelo Salemi Viana - algoritmo de reconstru��o EM',10,...
    'Ronaldo Vitor Reis Matos -  tBAC experimental',10,...
    'Ellem Floride Flauzino - tBAC experimental',10,...
    'Murilo Stelzer - BAC',10,...
    'Jos� Ricardo Arruda Miranda - BAC',10,10,10,10,...
    '::AGRADECIMENTOS:',10,10,...
    'Unesp',20,...
    'Unifeb ',10,10,...
    'Fapesp',20,...
    'CAPES',20,...
    'CNPq'];
uicontrol(gcf,'Style','text',...
                'String',texto,...
                'Position',[0 0 500 500],...
                'Max',255,'Min',0,...
                'Enable','inactive',...
                'FontSize',10,'BackGroundColor',[1 1 1]);
end

function back(varargin)
BACup;
end

function ultimat(varargin)
clf;BACmenu(gcf);
uicontrol(gcf,'Style','text',...
                'String','Ultimas atualizacoes',...
                'Position',[0 200 500 300],...
                'FontSize',10,'BackGroundColor',[1 1 1]);
a=BACat(2000);
uicontrol(gcf,'Style','edit',...
                'String',a,...
                'Position',[0 0 500 400],...
                'Max',255,'Min',0,...
                'Enable','inactive',...
                'HorizontalAlignment','left',...
                'FontSize',9,'BackGroundColor',[1 1 1]);
end

% acao sair
function sair(hObject,EventData) %#ok<INUSD>
% close(999)%(gcbf)
    selection = ...
       questdlg(['Sair de ' get(gcbf,'Name') '?'],...
                ['Sair de ' get(gcbf,'Name') '...'],...
                'Sim','N�o','Sim');
    if strcmp(selection,'N�o')
        return;
    else
        delete(gcbf);
        clc
        [y, m, d, h, mn, s] = datevec(now);
        disp([':: Obrigado por usar BACBox',10,10,'Atividades encerradas em  ',num2str(d),'/',num2str(m),'/',...
            num2str(y),' �s ',num2str(h),':',num2str(mn),':',num2str(round(s))])
    end
end
